/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root'
import { Route as IndexRouteImport } from './modules/home/routes/index'
import { Route as AboutRouteImport } from './modules/home/routes/about'
import { Route as OrganizationSlugShellRouteImport } from './modules/org-dashboard/routes/_shell'
import { Route as AccountShellRouteImport } from './modules/account-dashboard/routes/_shell'
import { Route as AuthForgotPasswordRouteImport } from './modules/auth/routes/forgot-password'
import { Route as AuthLoginRouteImport } from './modules/auth/routes/login'
import { Route as AuthPostloginRouteImport } from './modules/auth/routes/postlogin'
import { Route as AuthRegisterRouteImport } from './modules/auth/routes/register'
import { Route as AuthResetPasswordRouteImport } from './modules/auth/routes/reset-password'
import { Route as CheckoutSuccessRouteImport } from './modules/checkout/routes/success'
import { Route as OrganizationsNewRouteImport } from './modules/organizations/routes/new'
import { Route as OrganizationSlugShellDotindexRouteImport } from './modules/org-dashboard/routes/_shell.index'
import { Route as OrganizationSlugShellDotanalyticsRouteImport } from './modules/org-dashboard/routes/_shell.analytics'
import { Route as OrganizationSlugShellDotpaymentsRouteImport } from './modules/org-dashboard/routes/_shell.payments'
import { Route as OrganizationSlugShellDotteamRouteImport } from './modules/org-dashboard/routes/_shell.team'
import { Route as AccountShellDotindexRouteImport } from './modules/account-dashboard/routes/_shell.index'
import { Route as AccountShellDotnotificationsRouteImport } from './modules/account-dashboard/routes/_shell.notifications'
import { Route as AccountShellDotorganizationsRouteImport } from './modules/account-dashboard/routes/_shell.organizations'
import { Route as AccountShellDotpaymentsRouteImport } from './modules/account-dashboard/routes/_shell.payments'
import { Route as AccountShellDotsettingsRouteImport } from './modules/account-dashboard/routes/_shell.settings'
import { Route as OrganizationsIdDotonboardingRouteImport } from './modules/organizations/routes/$id.onboarding'
import { Route as OrganizationsIdDotplanRouteImport } from './modules/organizations/routes/$id.plan'
import { Route as OrganizationSlugShellDotbookingsDotindexRouteImport } from './modules/org-dashboard/routes/_shell.bookings.index'
import { Route as OrganizationSlugShellDotbookingsDotidRouteImport } from './modules/org-dashboard/routes/_shell.bookings.$id'
import { Route as OrganizationSlugShellDotcustomersDotindexRouteImport } from './modules/org-dashboard/routes/_shell.customers.index'
import { Route as OrganizationSlugShellDotcustomersDotidRouteImport } from './modules/org-dashboard/routes/_shell.customers.$id'
import { Route as OrganizationSlugShellDotpagesDotindexRouteImport } from './modules/org-dashboard/routes/_shell.pages.index'
import { Route as OrganizationSlugShellDotpagesDotidRouteImport } from './modules/org-dashboard/routes/_shell.pages.$id'
import { Route as OrganizationSlugShellDotservicesDotindexRouteImport } from './modules/org-dashboard/routes/_shell.services.index'
import { Route as OrganizationSlugShellDotservicesDotidRouteImport } from './modules/org-dashboard/routes/_shell.services.$id'
import { Route as OrganizationSlugShellDotsettingsDotindexRouteImport } from './modules/org-dashboard/routes/_shell.settings.index'
import { Route as OrganizationSlugShellDotsettingsDotbillingRouteImport } from './modules/org-dashboard/routes/_shell.settings.billing'
import { Route as AccountShellDotbookingsDotindexRouteImport } from './modules/account-dashboard/routes/_shell.bookings.index'
import { Route as AccountShellDotbookingsDotidRouteImport } from './modules/account-dashboard/routes/_shell.bookings.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSlugShellRoute = OrganizationSlugShellRouteImport.update({
  id: '/$organizationSlug/_shell',
  path: '/$organizationSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountShellRoute = AccountShellRouteImport.update({
  id: '/account/_shell',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPostloginRoute = AuthPostloginRouteImport.update({
  id: '/auth/postlogin',
  path: '/auth/postlogin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSlugShellDotindexRoute =
  OrganizationSlugShellDotindexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrganizationSlugShellRoute,
  } as any)
const OrganizationSlugShellDotanalyticsRoute =
  OrganizationSlugShellDotanalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => OrganizationSlugShellRoute,
  } as any)
const OrganizationSlugShellDotpaymentsRoute =
  OrganizationSlugShellDotpaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => OrganizationSlugShellRoute,
  } as any)
const OrganizationSlugShellDotteamRoute =
  OrganizationSlugShellDotteamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => OrganizationSlugShellRoute,
  } as any)
const AccountShellDotindexRoute = AccountShellDotindexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountShellRoute,
} as any)
const AccountShellDotnotificationsRoute =
  AccountShellDotnotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AccountShellRoute,
  } as any)
const AccountShellDotorganizationsRoute =
  AccountShellDotorganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AccountShellRoute,
  } as any)
const AccountShellDotpaymentsRoute = AccountShellDotpaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AccountShellRoute,
} as any)
const AccountShellDotsettingsRoute = AccountShellDotsettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountShellRoute,
} as any)
const OrganizationsIdDotonboardingRoute =
  OrganizationsIdDotonboardingRouteImport.update({
    id: '/organizations/$id/onboarding',
    path: '/organizations/$id/onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsIdDotplanRoute = OrganizationsIdDotplanRouteImport.update({
  id: '/organizations/$id/plan',
  path: '/organizations/$id/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSlugShellDotbookingsDotindexRoute =
  OrganizationSlugShellDotbookingsDotindexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => OrganizationSlugShellRoute,
  } as any)
const OrganizationSlugShellDotbookingsDotidRoute =
  OrganizationSlugShellDotbookingsDotidRouteImport.update({
    id: '/bookings/$id',
    path: '/bookings/$id',
    getParentRoute: () => OrganizationSlugShellRoute,
  } as any)
const OrganizationSlugShellDotcustomersDotindexRoute =
  OrganizationSlugShellDotcustomersDotindexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => OrganizationSlugShellRoute,
  } as any)
const OrganizationSlugShellDotcustomersDotidRoute =
  OrganizationSlugShellDotcustomersDotidRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => OrganizationSlugShellRoute,
  } as any)
const OrganizationSlugShellDotpagesDotindexRoute =
  OrganizationSlugShellDotpagesDotindexRouteImport.update({
    id: '/pages/',
    path: '/pages/',
    getParentRoute: () => OrganizationSlugShellRoute,
  } as any)
const OrganizationSlugShellDotpagesDotidRoute =
  OrganizationSlugShellDotpagesDotidRouteImport.update({
    id: '/pages/$id',
    path: '/pages/$id',
    getParentRoute: () => OrganizationSlugShellRoute,
  } as any)
const OrganizationSlugShellDotservicesDotindexRoute =
  OrganizationSlugShellDotservicesDotindexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => OrganizationSlugShellRoute,
  } as any)
const OrganizationSlugShellDotservicesDotidRoute =
  OrganizationSlugShellDotservicesDotidRouteImport.update({
    id: '/services/$id',
    path: '/services/$id',
    getParentRoute: () => OrganizationSlugShellRoute,
  } as any)
const OrganizationSlugShellDotsettingsDotindexRoute =
  OrganizationSlugShellDotsettingsDotindexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => OrganizationSlugShellRoute,
  } as any)
const OrganizationSlugShellDotsettingsDotbillingRoute =
  OrganizationSlugShellDotsettingsDotbillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => OrganizationSlugShellRoute,
  } as any)
const AccountShellDotbookingsDotindexRoute =
  AccountShellDotbookingsDotindexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AccountShellRoute,
  } as any)
const AccountShellDotbookingsDotidRoute =
  AccountShellDotbookingsDotidRouteImport.update({
    id: '/bookings/$id',
    path: '/bookings/$id',
    getParentRoute: () => AccountShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/$organizationSlug': typeof OrganizationSlugShellRouteWithChildren
  '/account': typeof AccountShellRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/postlogin': typeof AuthPostloginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/$organizationSlug/analytics': typeof OrganizationSlugShellDotanalyticsRoute
  '/$organizationSlug/payments': typeof OrganizationSlugShellDotpaymentsRoute
  '/$organizationSlug/team': typeof OrganizationSlugShellDotteamRoute
  '/account/notifications': typeof AccountShellDotnotificationsRoute
  '/account/organizations': typeof AccountShellDotorganizationsRoute
  '/account/payments': typeof AccountShellDotpaymentsRoute
  '/account/settings': typeof AccountShellDotsettingsRoute
  '/organizations/$id/onboarding': typeof OrganizationsIdDotonboardingRoute
  '/organizations/$id/plan': typeof OrganizationsIdDotplanRoute
  '/$organizationSlug/': typeof OrganizationSlugShellDotindexRoute
  '/account/': typeof AccountShellDotindexRoute
  '/$organizationSlug/bookings/$id': typeof OrganizationSlugShellDotbookingsDotidRoute
  '/$organizationSlug/customers/$id': typeof OrganizationSlugShellDotcustomersDotidRoute
  '/$organizationSlug/pages/$id': typeof OrganizationSlugShellDotpagesDotidRoute
  '/$organizationSlug/services/$id': typeof OrganizationSlugShellDotservicesDotidRoute
  '/$organizationSlug/settings/billing': typeof OrganizationSlugShellDotsettingsDotbillingRoute
  '/account/bookings/$id': typeof AccountShellDotbookingsDotidRoute
  '/$organizationSlug/bookings/': typeof OrganizationSlugShellDotbookingsDotindexRoute
  '/$organizationSlug/customers/': typeof OrganizationSlugShellDotcustomersDotindexRoute
  '/$organizationSlug/pages/': typeof OrganizationSlugShellDotpagesDotindexRoute
  '/$organizationSlug/services/': typeof OrganizationSlugShellDotservicesDotindexRoute
  '/$organizationSlug/settings/': typeof OrganizationSlugShellDotsettingsDotindexRoute
  '/account/bookings/': typeof AccountShellDotbookingsDotindexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/postlogin': typeof AuthPostloginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/$organizationSlug/analytics': typeof OrganizationSlugShellDotanalyticsRoute
  '/$organizationSlug/payments': typeof OrganizationSlugShellDotpaymentsRoute
  '/$organizationSlug/team': typeof OrganizationSlugShellDotteamRoute
  '/account/notifications': typeof AccountShellDotnotificationsRoute
  '/account/organizations': typeof AccountShellDotorganizationsRoute
  '/account/payments': typeof AccountShellDotpaymentsRoute
  '/account/settings': typeof AccountShellDotsettingsRoute
  '/organizations/$id/onboarding': typeof OrganizationsIdDotonboardingRoute
  '/organizations/$id/plan': typeof OrganizationsIdDotplanRoute
  '/$organizationSlug': typeof OrganizationSlugShellDotindexRoute
  '/account': typeof AccountShellDotindexRoute
  '/$organizationSlug/bookings/$id': typeof OrganizationSlugShellDotbookingsDotidRoute
  '/$organizationSlug/customers/$id': typeof OrganizationSlugShellDotcustomersDotidRoute
  '/$organizationSlug/pages/$id': typeof OrganizationSlugShellDotpagesDotidRoute
  '/$organizationSlug/services/$id': typeof OrganizationSlugShellDotservicesDotidRoute
  '/$organizationSlug/settings/billing': typeof OrganizationSlugShellDotsettingsDotbillingRoute
  '/account/bookings/$id': typeof AccountShellDotbookingsDotidRoute
  '/$organizationSlug/bookings': typeof OrganizationSlugShellDotbookingsDotindexRoute
  '/$organizationSlug/customers': typeof OrganizationSlugShellDotcustomersDotindexRoute
  '/$organizationSlug/pages': typeof OrganizationSlugShellDotpagesDotindexRoute
  '/$organizationSlug/services': typeof OrganizationSlugShellDotservicesDotindexRoute
  '/$organizationSlug/settings': typeof OrganizationSlugShellDotsettingsDotindexRoute
  '/account/bookings': typeof AccountShellDotbookingsDotindexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/$organizationSlug/_shell': typeof OrganizationSlugShellRouteWithChildren
  '/account/_shell': typeof AccountShellRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/postlogin': typeof AuthPostloginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/$organizationSlug/_shell/analytics': typeof OrganizationSlugShellDotanalyticsRoute
  '/$organizationSlug/_shell/payments': typeof OrganizationSlugShellDotpaymentsRoute
  '/$organizationSlug/_shell/team': typeof OrganizationSlugShellDotteamRoute
  '/account/_shell/notifications': typeof AccountShellDotnotificationsRoute
  '/account/_shell/organizations': typeof AccountShellDotorganizationsRoute
  '/account/_shell/payments': typeof AccountShellDotpaymentsRoute
  '/account/_shell/settings': typeof AccountShellDotsettingsRoute
  '/organizations/$id/onboarding': typeof OrganizationsIdDotonboardingRoute
  '/organizations/$id/plan': typeof OrganizationsIdDotplanRoute
  '/$organizationSlug/_shell/': typeof OrganizationSlugShellDotindexRoute
  '/account/_shell/': typeof AccountShellDotindexRoute
  '/$organizationSlug/_shell/bookings/$id': typeof OrganizationSlugShellDotbookingsDotidRoute
  '/$organizationSlug/_shell/customers/$id': typeof OrganizationSlugShellDotcustomersDotidRoute
  '/$organizationSlug/_shell/pages/$id': typeof OrganizationSlugShellDotpagesDotidRoute
  '/$organizationSlug/_shell/services/$id': typeof OrganizationSlugShellDotservicesDotidRoute
  '/$organizationSlug/_shell/settings/billing': typeof OrganizationSlugShellDotsettingsDotbillingRoute
  '/account/_shell/bookings/$id': typeof AccountShellDotbookingsDotidRoute
  '/$organizationSlug/_shell/bookings/': typeof OrganizationSlugShellDotbookingsDotindexRoute
  '/$organizationSlug/_shell/customers/': typeof OrganizationSlugShellDotcustomersDotindexRoute
  '/$organizationSlug/_shell/pages/': typeof OrganizationSlugShellDotpagesDotindexRoute
  '/$organizationSlug/_shell/services/': typeof OrganizationSlugShellDotservicesDotindexRoute
  '/$organizationSlug/_shell/settings/': typeof OrganizationSlugShellDotsettingsDotindexRoute
  '/account/_shell/bookings/': typeof AccountShellDotbookingsDotindexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/$organizationSlug'
    | '/account'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/postlogin'
    | '/auth/register'
    | '/auth/reset-password'
    | '/checkout/success'
    | '/organizations/new'
    | '/$organizationSlug/analytics'
    | '/$organizationSlug/payments'
    | '/$organizationSlug/team'
    | '/account/notifications'
    | '/account/organizations'
    | '/account/payments'
    | '/account/settings'
    | '/organizations/$id/onboarding'
    | '/organizations/$id/plan'
    | '/$organizationSlug/'
    | '/account/'
    | '/$organizationSlug/bookings/$id'
    | '/$organizationSlug/customers/$id'
    | '/$organizationSlug/pages/$id'
    | '/$organizationSlug/services/$id'
    | '/$organizationSlug/settings/billing'
    | '/account/bookings/$id'
    | '/$organizationSlug/bookings/'
    | '/$organizationSlug/customers/'
    | '/$organizationSlug/pages/'
    | '/$organizationSlug/services/'
    | '/$organizationSlug/settings/'
    | '/account/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/postlogin'
    | '/auth/register'
    | '/auth/reset-password'
    | '/checkout/success'
    | '/organizations/new'
    | '/$organizationSlug/analytics'
    | '/$organizationSlug/payments'
    | '/$organizationSlug/team'
    | '/account/notifications'
    | '/account/organizations'
    | '/account/payments'
    | '/account/settings'
    | '/organizations/$id/onboarding'
    | '/organizations/$id/plan'
    | '/$organizationSlug'
    | '/account'
    | '/$organizationSlug/bookings/$id'
    | '/$organizationSlug/customers/$id'
    | '/$organizationSlug/pages/$id'
    | '/$organizationSlug/services/$id'
    | '/$organizationSlug/settings/billing'
    | '/account/bookings/$id'
    | '/$organizationSlug/bookings'
    | '/$organizationSlug/customers'
    | '/$organizationSlug/pages'
    | '/$organizationSlug/services'
    | '/$organizationSlug/settings'
    | '/account/bookings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/$organizationSlug/_shell'
    | '/account/_shell'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/postlogin'
    | '/auth/register'
    | '/auth/reset-password'
    | '/checkout/success'
    | '/organizations/new'
    | '/$organizationSlug/_shell/analytics'
    | '/$organizationSlug/_shell/payments'
    | '/$organizationSlug/_shell/team'
    | '/account/_shell/notifications'
    | '/account/_shell/organizations'
    | '/account/_shell/payments'
    | '/account/_shell/settings'
    | '/organizations/$id/onboarding'
    | '/organizations/$id/plan'
    | '/$organizationSlug/_shell/'
    | '/account/_shell/'
    | '/$organizationSlug/_shell/bookings/$id'
    | '/$organizationSlug/_shell/customers/$id'
    | '/$organizationSlug/_shell/pages/$id'
    | '/$organizationSlug/_shell/services/$id'
    | '/$organizationSlug/_shell/settings/billing'
    | '/account/_shell/bookings/$id'
    | '/$organizationSlug/_shell/bookings/'
    | '/$organizationSlug/_shell/customers/'
    | '/$organizationSlug/_shell/pages/'
    | '/$organizationSlug/_shell/services/'
    | '/$organizationSlug/_shell/settings/'
    | '/account/_shell/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  OrganizationSlugShellRoute: typeof OrganizationSlugShellRouteWithChildren
  AccountShellRoute: typeof AccountShellRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPostloginRoute: typeof AuthPostloginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  OrganizationsNewRoute: typeof OrganizationsNewRoute
  OrganizationsIdDotonboardingRoute: typeof OrganizationsIdDotonboardingRoute
  OrganizationsIdDotplanRoute: typeof OrganizationsIdDotplanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationSlug/_shell': {
      id: '/$organizationSlug/_shell'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof OrganizationSlugShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/_shell': {
      id: '/account/_shell'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/postlogin': {
      id: '/auth/postlogin'
      path: '/auth/postlogin'
      fullPath: '/auth/postlogin'
      preLoaderRoute: typeof AuthPostloginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationSlug/_shell/': {
      id: '/$organizationSlug/_shell/'
      path: '/'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof OrganizationSlugShellDotindexRouteImport
      parentRoute: typeof OrganizationSlugShellRoute
    }
    '/$organizationSlug/_shell/analytics': {
      id: '/$organizationSlug/_shell/analytics'
      path: '/analytics'
      fullPath: '/$organizationSlug/analytics'
      preLoaderRoute: typeof OrganizationSlugShellDotanalyticsRouteImport
      parentRoute: typeof OrganizationSlugShellRoute
    }
    '/$organizationSlug/_shell/payments': {
      id: '/$organizationSlug/_shell/payments'
      path: '/payments'
      fullPath: '/$organizationSlug/payments'
      preLoaderRoute: typeof OrganizationSlugShellDotpaymentsRouteImport
      parentRoute: typeof OrganizationSlugShellRoute
    }
    '/$organizationSlug/_shell/team': {
      id: '/$organizationSlug/_shell/team'
      path: '/team'
      fullPath: '/$organizationSlug/team'
      preLoaderRoute: typeof OrganizationSlugShellDotteamRouteImport
      parentRoute: typeof OrganizationSlugShellRoute
    }
    '/account/_shell/': {
      id: '/account/_shell/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountShellDotindexRouteImport
      parentRoute: typeof AccountShellRoute
    }
    '/account/_shell/notifications': {
      id: '/account/_shell/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountShellDotnotificationsRouteImport
      parentRoute: typeof AccountShellRoute
    }
    '/account/_shell/organizations': {
      id: '/account/_shell/organizations'
      path: '/organizations'
      fullPath: '/account/organizations'
      preLoaderRoute: typeof AccountShellDotorganizationsRouteImport
      parentRoute: typeof AccountShellRoute
    }
    '/account/_shell/payments': {
      id: '/account/_shell/payments'
      path: '/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AccountShellDotpaymentsRouteImport
      parentRoute: typeof AccountShellRoute
    }
    '/account/_shell/settings': {
      id: '/account/_shell/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountShellDotsettingsRouteImport
      parentRoute: typeof AccountShellRoute
    }
    '/organizations/$id/onboarding': {
      id: '/organizations/$id/onboarding'
      path: '/organizations/$id/onboarding'
      fullPath: '/organizations/$id/onboarding'
      preLoaderRoute: typeof OrganizationsIdDotonboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$id/plan': {
      id: '/organizations/$id/plan'
      path: '/organizations/$id/plan'
      fullPath: '/organizations/$id/plan'
      preLoaderRoute: typeof OrganizationsIdDotplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationSlug/_shell/bookings/': {
      id: '/$organizationSlug/_shell/bookings/'
      path: '/bookings'
      fullPath: '/$organizationSlug/bookings/'
      preLoaderRoute: typeof OrganizationSlugShellDotbookingsDotindexRouteImport
      parentRoute: typeof OrganizationSlugShellRoute
    }
    '/$organizationSlug/_shell/bookings/$id': {
      id: '/$organizationSlug/_shell/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/$organizationSlug/bookings/$id'
      preLoaderRoute: typeof OrganizationSlugShellDotbookingsDotidRouteImport
      parentRoute: typeof OrganizationSlugShellRoute
    }
    '/$organizationSlug/_shell/customers/': {
      id: '/$organizationSlug/_shell/customers/'
      path: '/customers'
      fullPath: '/$organizationSlug/customers/'
      preLoaderRoute: typeof OrganizationSlugShellDotcustomersDotindexRouteImport
      parentRoute: typeof OrganizationSlugShellRoute
    }
    '/$organizationSlug/_shell/customers/$id': {
      id: '/$organizationSlug/_shell/customers/$id'
      path: '/customers/$id'
      fullPath: '/$organizationSlug/customers/$id'
      preLoaderRoute: typeof OrganizationSlugShellDotcustomersDotidRouteImport
      parentRoute: typeof OrganizationSlugShellRoute
    }
    '/$organizationSlug/_shell/pages/': {
      id: '/$organizationSlug/_shell/pages/'
      path: '/pages'
      fullPath: '/$organizationSlug/pages/'
      preLoaderRoute: typeof OrganizationSlugShellDotpagesDotindexRouteImport
      parentRoute: typeof OrganizationSlugShellRoute
    }
    '/$organizationSlug/_shell/pages/$id': {
      id: '/$organizationSlug/_shell/pages/$id'
      path: '/pages/$id'
      fullPath: '/$organizationSlug/pages/$id'
      preLoaderRoute: typeof OrganizationSlugShellDotpagesDotidRouteImport
      parentRoute: typeof OrganizationSlugShellRoute
    }
    '/$organizationSlug/_shell/services/': {
      id: '/$organizationSlug/_shell/services/'
      path: '/services'
      fullPath: '/$organizationSlug/services/'
      preLoaderRoute: typeof OrganizationSlugShellDotservicesDotindexRouteImport
      parentRoute: typeof OrganizationSlugShellRoute
    }
    '/$organizationSlug/_shell/services/$id': {
      id: '/$organizationSlug/_shell/services/$id'
      path: '/services/$id'
      fullPath: '/$organizationSlug/services/$id'
      preLoaderRoute: typeof OrganizationSlugShellDotservicesDotidRouteImport
      parentRoute: typeof OrganizationSlugShellRoute
    }
    '/$organizationSlug/_shell/settings/': {
      id: '/$organizationSlug/_shell/settings/'
      path: '/settings'
      fullPath: '/$organizationSlug/settings/'
      preLoaderRoute: typeof OrganizationSlugShellDotsettingsDotindexRouteImport
      parentRoute: typeof OrganizationSlugShellRoute
    }
    '/$organizationSlug/_shell/settings/billing': {
      id: '/$organizationSlug/_shell/settings/billing'
      path: '/settings/billing'
      fullPath: '/$organizationSlug/settings/billing'
      preLoaderRoute: typeof OrganizationSlugShellDotsettingsDotbillingRouteImport
      parentRoute: typeof OrganizationSlugShellRoute
    }
    '/account/_shell/bookings/': {
      id: '/account/_shell/bookings/'
      path: '/bookings'
      fullPath: '/account/bookings/'
      preLoaderRoute: typeof AccountShellDotbookingsDotindexRouteImport
      parentRoute: typeof AccountShellRoute
    }
    '/account/_shell/bookings/$id': {
      id: '/account/_shell/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/account/bookings/$id'
      preLoaderRoute: typeof AccountShellDotbookingsDotidRouteImport
      parentRoute: typeof AccountShellRoute
    }
  }
}

interface OrganizationSlugShellRouteChildren {
  OrganizationSlugShellDotanalyticsRoute: typeof OrganizationSlugShellDotanalyticsRoute
  OrganizationSlugShellDotpaymentsRoute: typeof OrganizationSlugShellDotpaymentsRoute
  OrganizationSlugShellDotteamRoute: typeof OrganizationSlugShellDotteamRoute
  OrganizationSlugShellDotindexRoute: typeof OrganizationSlugShellDotindexRoute
  OrganizationSlugShellDotbookingsDotidRoute: typeof OrganizationSlugShellDotbookingsDotidRoute
  OrganizationSlugShellDotcustomersDotidRoute: typeof OrganizationSlugShellDotcustomersDotidRoute
  OrganizationSlugShellDotpagesDotidRoute: typeof OrganizationSlugShellDotpagesDotidRoute
  OrganizationSlugShellDotservicesDotidRoute: typeof OrganizationSlugShellDotservicesDotidRoute
  OrganizationSlugShellDotsettingsDotbillingRoute: typeof OrganizationSlugShellDotsettingsDotbillingRoute
  OrganizationSlugShellDotbookingsDotindexRoute: typeof OrganizationSlugShellDotbookingsDotindexRoute
  OrganizationSlugShellDotcustomersDotindexRoute: typeof OrganizationSlugShellDotcustomersDotindexRoute
  OrganizationSlugShellDotpagesDotindexRoute: typeof OrganizationSlugShellDotpagesDotindexRoute
  OrganizationSlugShellDotservicesDotindexRoute: typeof OrganizationSlugShellDotservicesDotindexRoute
  OrganizationSlugShellDotsettingsDotindexRoute: typeof OrganizationSlugShellDotsettingsDotindexRoute
}

const OrganizationSlugShellRouteChildren: OrganizationSlugShellRouteChildren = {
  OrganizationSlugShellDotanalyticsRoute:
    OrganizationSlugShellDotanalyticsRoute,
  OrganizationSlugShellDotpaymentsRoute: OrganizationSlugShellDotpaymentsRoute,
  OrganizationSlugShellDotteamRoute: OrganizationSlugShellDotteamRoute,
  OrganizationSlugShellDotindexRoute: OrganizationSlugShellDotindexRoute,
  OrganizationSlugShellDotbookingsDotidRoute:
    OrganizationSlugShellDotbookingsDotidRoute,
  OrganizationSlugShellDotcustomersDotidRoute:
    OrganizationSlugShellDotcustomersDotidRoute,
  OrganizationSlugShellDotpagesDotidRoute:
    OrganizationSlugShellDotpagesDotidRoute,
  OrganizationSlugShellDotservicesDotidRoute:
    OrganizationSlugShellDotservicesDotidRoute,
  OrganizationSlugShellDotsettingsDotbillingRoute:
    OrganizationSlugShellDotsettingsDotbillingRoute,
  OrganizationSlugShellDotbookingsDotindexRoute:
    OrganizationSlugShellDotbookingsDotindexRoute,
  OrganizationSlugShellDotcustomersDotindexRoute:
    OrganizationSlugShellDotcustomersDotindexRoute,
  OrganizationSlugShellDotpagesDotindexRoute:
    OrganizationSlugShellDotpagesDotindexRoute,
  OrganizationSlugShellDotservicesDotindexRoute:
    OrganizationSlugShellDotservicesDotindexRoute,
  OrganizationSlugShellDotsettingsDotindexRoute:
    OrganizationSlugShellDotsettingsDotindexRoute,
}

const OrganizationSlugShellRouteWithChildren =
  OrganizationSlugShellRoute._addFileChildren(
    OrganizationSlugShellRouteChildren,
  )

interface AccountShellRouteChildren {
  AccountShellDotnotificationsRoute: typeof AccountShellDotnotificationsRoute
  AccountShellDotorganizationsRoute: typeof AccountShellDotorganizationsRoute
  AccountShellDotpaymentsRoute: typeof AccountShellDotpaymentsRoute
  AccountShellDotsettingsRoute: typeof AccountShellDotsettingsRoute
  AccountShellDotindexRoute: typeof AccountShellDotindexRoute
  AccountShellDotbookingsDotidRoute: typeof AccountShellDotbookingsDotidRoute
  AccountShellDotbookingsDotindexRoute: typeof AccountShellDotbookingsDotindexRoute
}

const AccountShellRouteChildren: AccountShellRouteChildren = {
  AccountShellDotnotificationsRoute: AccountShellDotnotificationsRoute,
  AccountShellDotorganizationsRoute: AccountShellDotorganizationsRoute,
  AccountShellDotpaymentsRoute: AccountShellDotpaymentsRoute,
  AccountShellDotsettingsRoute: AccountShellDotsettingsRoute,
  AccountShellDotindexRoute: AccountShellDotindexRoute,
  AccountShellDotbookingsDotidRoute: AccountShellDotbookingsDotidRoute,
  AccountShellDotbookingsDotindexRoute: AccountShellDotbookingsDotindexRoute,
}

const AccountShellRouteWithChildren = AccountShellRoute._addFileChildren(
  AccountShellRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  OrganizationSlugShellRoute: OrganizationSlugShellRouteWithChildren,
  AccountShellRoute: AccountShellRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPostloginRoute: AuthPostloginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  OrganizationsNewRoute: OrganizationsNewRoute,
  OrganizationsIdDotonboardingRoute: OrganizationsIdDotonboardingRoute,
  OrganizationsIdDotplanRoute: OrganizationsIdDotplanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
